var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var idText = new Schema({
    id:Schema.Types.String,
    text:Schema.Types.String
});

/**
 * 定义emrsIndex对象模型
 */
var emrsIndexSchema = new Schema({
    genderList:[idText],
    alopeciaParts:[idText],
    anginaTypes:[idText],
    arrhythmiaTypes:[idText],
    bleedingCauses:[idText],
    bloodTypes:[idText],
    breathSoundsParts: [idText],
    breathSoundsTypes: [idText],
    cardiacRhythms: [idText],
    cigretteTypes: [idText],
    contrastMedia: [idText],
    coronaryDistributionTypes: [idText],
    deepVenousThrombosisDiagnosisResults: [idText],
    deepVenousThrombosisInducements: [idText],
    deepVenousThrombosisSymptoms: [idText],
    diabetesMellitusTreatmentMethods: [idText],
    dietHabitAquaticProducts: [idText],
    dietHabitDrinkingAmouts: [idText],
    dietHabitEggs: [idText],
    dietHabitFruits: [idText],
    dietHabitGrainMixedBeans: [idText],
    dietHabitLivestockMeats: [idText],
    dietHabitMilkProducts: [idText],
    dietHabitOils: [idText],
    dietHabitPaddyPotatoes: [idText],
    dietHabitPotatoes: [idText],
    dietHabitSalts: [idText],
    dietHabitSoybeansNuts: [idText],
    dietHabitSugar: [idText],
    dietHabitVegetables: [idText],
    diseaseBodyPartNames: [idText],
    diseaseDurationOfPain: [idText],
    diseasePainDegree: [idText],
    diseaseQualityOfPain: [idText],
    dysglycemiaTypes: [idText],
    diabetesMellitusTypes: [idText],
    earLobeLongitudinalCrackParts: [idText],
    ecgResults: [idText],
    ecgWaveforms: [idText],
    exerciseDuration: [idText],
    exerciseModes: [idText],
    exerciseTypes: [idText],
    familyHistoryDiseaseNames: [idText],
    familyMembers: [idText],
    heartSoundS1Results: [idText],
    hemorrhageTypes: [idText],
    historyOfPresentIllnessCareCauses: [idText],
    leadSystem: [idText],
    lipidAbnormalityTypes: [idText],
    lungWetRalesParts: [idText],
    lungWetRalesRanges: [idText],
    myocardialInfarctionTypes: [idText],
    oldIschemicStrokeTypes: [idText],
    oldMyocardialInfarctionLocations: [idText],
    onsetTimeOfIllness: [idText],
    otherHeartDiseaseTypes: [idText],
    pciPaths: [idText],
    pciTypes: [idText],
    precipitatingFactors: [idText],
    prematureChdTypes: [idText],
    radiationSites: [idText],
    relievingFactors: [idText],
    segmentalLesionsShapes: [idText],
    simultaneousPhenomena: [idText],
    skinYellowPigmentTumorParts: [idText],
    suddenDeathEtiologies: [idText],
    ucgParts: [idText],
    vascularDiseasesTypes: [idText],
    wineTypes: [idText],
    nationalityList: [idText],
    professionList: [idText]
});

module.exports = mongoose.model('emrsIndexe', emrsIndexSchema);