var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var type = Schema.Types;

/**
 * 定义record对象模型
 */
var recordSchema = new Schema({
    basicInfo: {
        admissionNum: type.String,
        bedNum: type.String,
        doctorId: type.String,
        recorderId: type.String,
        name: type.String,
        medicalCardNum: type.String,
        idNum: type.String,
        cellphone1: type.String,
        cellphone2: type.String,
        telephone: type.String,
        gender: type.String,
        nationality: type.String,
        birthProvince: type.String,
        birthCity: type.String,
        birthday: type.String,
        profession: type.String,
        addressProvince: type.String,
        addressCity: type.String,
        addressArea: type.String,
        addressTown: type.String,
        address: type.String
    },
    historyOfPresentIllness: {
        careCauses: type.String,
        careCauseOthers: type.String,
        chestPain: {
            timesPerDay: type.String,
            timesPerWeek: type.String,
            timesPerMonth: type.String,
            timesPerYear: type.String,
            onsetTime: type.String,
            onsetTimeOthers: type.String,
            diseaseBodyParts: [
                {
                    bodyPartName: type.String,
                    bodyPartNameOthers: type.String,
                    qualityOfPain: type.String,
                    qualityOfPainOthers: type.String,
                    durationOfPain: type.String,
                    durationOfPainOthers: type.String,
                    painDegree: type.String
                }
            ],
            relievingFactors: type.String,
            relievingFactorsOthers: type.String,
            precipitatingFactors: type.String,
            precipitatingFactorsOthers: type.String,
            radiationSites: type.String,
            radiationSitesOthers: type.String,
            simultaneousPhenomena: type.String,
            simultaneousPhenomenonOthers: type.String
        },
        chestDistress: {
            timesPerDay: type.String,
            timesPerWeek: type.String,
            timesPerMonth: type.String,
            timesPerYear: type.String,
            onsetTime: type.String,
            onsetTimeOthers: type.String,
            diseaseBodyParts: [
                {
                    bodyPartName: type.String,
                    bodyPartNameOthers: type.String,
                    qualityOfPain: type.String,
                    qualityOfPainOthers: type.String,
                    durationOfPain: type.String,
                    durationOfPainOthers: type.String,
                    painDegree: type.String
                }
            ],
            relievingFactors: type.String,
            relievingFactorsOthers: type.String,
            precipitatingFactors: type.String,
            precipitatingFactorsOthers: type.String,
            radiationSites: type.String,
            radiationSitesOthers: type.String,
            simultaneousPhenomena: type.String,
            simultaneousPhenomenonOthers: type.String
        },
        dyspnea: {
            timesPerDay: type.String,
            timesPerWeek: type.String,
            timesPerMonth: type.String,
            timesPerYear: type.String,
            onsetTime: type.String,
            onsetTimeOthers: type.String
        },
        palpitation: {
            timesPerDay: type.String,
            timesPerWeek: type.String,
            timesPerMonth: type.String,
            timesPerYear: type.String,
            onsetTime: type.String,
            onsetTimeOthers: type.String
        },
        abnormalEcg: {
            timesPerDay: type.String,
            timesPerWeek: type.String,
            timesPerMonth: type.String,
            timesPerYear: type.String,
            onsetTime: type.String,
            onsetTimeOthers: type.String
        }
    },
    anamnesis: {
        isLipidAbnormality: type.String,
        lipidAbnormalityType: type.String,
        lipidAbnormalityDuration: type.String,
        isLipidAbnormalityUnderTreatment: type.String,
        lipidAbnormalityDrugName: type.String,
        isEssentialHypertension: type.String,
        essentialHypertensionDuration: type.String,
        maximumValue: type.String,
        ordinaryValue: type.String,
        isEssentialHypertensionUnderTreatment: type.String,
        essentialHypertensionDrugName: type.String,
        isDysglycemia: type.String,
        dysglycemiaDuration: type.String,
        dysglycemiaType: type.String,
        isDiabetesMellitus: type.String,
        isDiabetesMellitusUnderTreatment: type.String,
        diabetesMellitusTreatmentMethod: type.String,
        diabetesMellitusOralDrugName: type.String,
        isGout: type.String,
        goutDuration: type.String,
        serumUricAcidLevel: type.String,
        isRenalInsufficiency: type.String,
        renalInsufficiencyDuration: type.String,
        maximumCr: type.String,
        recentCr: type.String,
        renalInsufficiencyEtiology: type.String,
        isOldMyocardialInfarction: type.String,
        oldMyocardialInfarctionOnsetTimeYear: type.String,
        oldMyocardialInfarctionOnsetTimeMonth: type.String,
        oldMyocardialInfarctionOnsetFrequency: type.String,
        oldMyocardialInfarctionLocation: type.String,
        oldMyocardialInfarctionLocationOthers: type.String,
        isPciHistory: type.String,
        isCabgHistory: type.String,
        isCasGt50History: type.String,
        isAtrialFibrillation: type.String,
        isOtherHeartDiseaseHistory: type.String,
        otherHeartDiseaseType: type.String,
        otherHeartDiseaseTypeOthers: type.String,
        isDeepVenousThrombosis: type.String,
        deepVenousThrombosisOnsetTimeYear: type.String,
        deepVenousThrombosisOnsetTimeMonth: type.String,
        deepVenousThrombosisInducements: type.String,
        deepVenousThrombosisSymptoms: type.String,
        deepVenousThrombosisDiagnosisResult: type.String,
        isOldIschemicStroke: type.String,
        oldIschemicStrokeTypes: [
            {
                typeName: type.String,
                onsetTimeYear: type.String,
                onsetTimeMonth: type.String,
                onsetFrequency: type.String
            }
        ],
        isVascularDiseases: type.String,
        vascularDiseasesTypes: type.String,
        isHemorrhage: type.String,
        hemorrhageTypes: [
            {
                typeName: type.String,
                onsetTime: type.String,
                onsetFrequency: type.String
            }
        ],
        isBleeding: type.String,
        bleedingCauses: [
            {
                cause: type.String,
                onsetTime: type.String
            }
        ]
    },
    riskFactors: {
        isSomking: type.String,
        smokingDuration: type.String,
        piecesPerDay: type.String,
        cigretteType: type.String,
        cigretteTypeOthers: type.String,
        isSmokingCessation: type.String,
        smokingCessationDuration: type.String,
        isDrinking: type.String,
        drinkingDuration: type.String,
        talesPerDay: type.String,
        wineType: type.String,
        wineTypeOthers: type.String,
        isTemperance: type.String,
        temperanceDuration: type.String,
        drinkingAmount: type.String,
        paddyPotato: type.String,
        grainMixedBeans: type.String,
        potato: type.String,
        vegetables: type.String,
        fruits: type.String,
        livestockMeat: type.String,
        aquaticProducts: type.String,
        eggs: type.String,
        milkProducts: type.String,
        soybeansNuts: type.String,
        salt: type.String,
        sugar: type.String,
        oil: type.String,
        fatMeat: type.String,
        visceral: type.String,
        bloodType: type.String,
        isLongtermPsychologicalStress: type.String,
        isDepression: type.String,
        exerciseType: type.String,
        exerciseDuration: type.String,
        exerciseMode: type.String,
        exerciseModeOthers: type.String,
        isCentralObesity: type.String,
        centralObesityDuration: type.String,
        height: type.String,
        weight: type.String,
        waistline: type.String,
        neckCircumference: type.String,
        hipline: type.String
    },
    familyHistory: {
        prematureChd: {
            isPrematureChd: type.String,
            onsetMembers: [
                {
                    onsetMember: type.String,
                    gender: type.String,
                    onsetAge: type.String,
                    prematureChdType: type.String
                }
            ]
        },
        myocardialInfarction: {
            ismyocardialInfarction: type.String,
            onsetMembers: [
                {
                    onsetMember: type.String,
                    gender: type.String,
                    onsetAge: type.String
                }
            ]
        },
        suddenDeath: {
            issuddenDeath: type.String,
            onsetMembers: [
                {
                    onsetMember: type.String,
                    gender: type.String,
                    onsetAge: type.String,
                    etiology: type.String,
                    etiologyOthers: type.String
                }
            ]
        },
        ischemicStroke: {
            isIschemicStroke: type.String,
            onsetMembers: [
                {
                    onsetMember: type.String,
                    gender: type.String,
                    onsetAge: type.String
                }
            ]
        },
        hemorrhagicStroke: {
            isHemorrhagicStroke: type.String,
            onsetMembers: [
                {
                    onsetMember: type.String,
                    gender: type.String,
                    onsetAge: type.String
                }
            ]
        }
    },
    physicalExamination: {
        bodyTemperature: type.String,
        respiratoryRate: type.String,
        isBreathSoundsNormal: type.String,
        breathSoundsType: type.String,
        breathSoundsPart: type.String,
        isLungWetRales: type.String,
        lungWetRalesRange: type.String,
        lungWetRalesPart: type.String,
        heartRate: type.String,
        cardiacRhythm: type.String,
        heartSoundS1Result: type.String,
        isS3S4GallopRhythm: type.String,
        pulse: type.String,
        bloodPressure: type.String,
        isEarLobeLongitudinalCrack: type.String,
        earLobeLongitudinalCrackParts: type.String,
        isSkinYellowPigmentTumor: type.String,
        skinYellowPigmentTumorParts: type.String,
        isAlopecia: type.String,
        alopeciaParts: type.String
    },
    routineExamination: {
        TC: type.String,
        TG: type.String,
        LDL: type.String,
        HDL: type.String,
        notHDL: type.String,
        bloodGlucoseFasting: type.String,
        isSerumMyocardialNecrosisMarkers: type.String,
        myocardialCK: type.String,
        myocardialCKMB: type.String,
        myocardialCTnI: type.String,
        myocardialMb: type.String,
        isInflammatoryMarkers: type.String,
        inflammationHsCRP: type.String,
        inflammationIL6: type.String,
        inflammationIL1Beta: type.String,
        inflammationTNFAlpha: type.String,
        heartFailureNTproBNP: type.String,
        electrolyteNa: type.String,
        electrolyteK: type.String,
        electrolyteCa: type.String,
        electrolyteCl: type.String,
        isLiverFunction: type.String,
        totalProtein: type.String,
        albumin: type.String,
        totalBilirubin: type.String,
        directBilirubin: type.String,
        indirectBilirubin: type.String,
        ALT: type.String,
        AST: type.String,
        isRenalFunction: type.String,
        Cr: type.String,
        UA: type.String,
        BUN: type.String,
        GFR: type.String,
        isHepatorenalDisease: type.String,
        APTT: type.String,
        PT: type.String,
        TT: type.String,
        FIB: type.String,
        dDimer: type.String,
        INR: type.String,
        isINRStable: type.String,
        redBloodCellCount: type.String,
        redBloodCellSpecificVolume: type.String,
        HGB: type.String,
        leukocyteCount: type.String,
        neutrophil: type.String,
        eosinophil: type.String,
        basophil: type.String,
        lymphocyte: type.String,
        monocyte: type.String,
        isQualitativePlatelet: type.String,
        plateletCountPLT: type.String,
        MPV: type.String,
        PDW: type.String,
        PARADP: type.String,
        PAREpinephrine: type.String,
        PARArachidonicAcid: type.String,
        PARCollagen: type.String,
        PARRistocetin: type.String
    },
    specialExamination: {
        ecg: {
            pathologicalQWave: {
                isPathologicalQWave: type.String,
                qWaveLeads: type.String
            },
            stSegmentChange: {
                isStSegmentChange: type.String,
                stSegmentDepression: {
                    isStSegmentDepression: type.String,
                    changeDetail: {
                        isLeadI: type.String,
                        leadIAmplitude: type.String,
                        isLeadII: type.String,
                        leadIIAmplitude: type.String,
                        isLeadIII: type.String,
                        leadIIIAmplitude: type.String,
                        isLeadAVF: type.String,
                        leadAVFAmplitude: type.String,
                        isLeadAVL: type.String,
                        leadAVLAmplitude: type.String,
                        isLeadAVR: type.String,
                        leadAVRAmplitude: type.String,
                        isLeadV1: type.String,
                        leadV1Amplitude: type.String,
                        isLeadV2: type.String,
                        leadV2Amplitude: type.String,
                        isLeadV3: type.String,
                        leadV3Amplitude: type.String,
                        isLeadV4: type.String,
                        leadV4Amplitude: type.String,
                        isLeadV5: type.String,
                        leadV5Amplitude: type.String,
                        isLeadV6: type.String,
                        leadV6Amplitude: type.String,
                        isLeadV7: type.String,
                        leadV7Amplitude: type.String,
                        isLeadV8: type.String,
                        leadV8Amplitude: type.String,
                        isLeadV9: type.String,
                        leadV9Amplitude: type.String
                    }
                },
                stSegmentElevation: {
                    isStSegmentElevation: type.String,
                    changeDetail: {
                        isLeadI: type.String,
                        leadIAmplitude: type.String,
                        isLeadII: type.String,
                        leadIIAmplitude: type.String,
                        isLeadIII: type.String,
                        leadIIIAmplitude: type.String,
                        isLeadAVF: type.String,
                        leadAVFAmplitude: type.String,
                        isLeadAVL: type.String,
                        leadAVLAmplitude: type.String,
                        isLeadAVR: type.String,
                        leadAVRAmplitude: type.String,
                        isLeadV1: type.String,
                        leadV1Amplitude: type.String,
                        isLeadV2: type.String,
                        leadV2Amplitude: type.String,
                        isLeadV3: type.String,
                        leadV3Amplitude: type.String,
                        isLeadV4: type.String,
                        leadV4Amplitude: type.String,
                        isLeadV5: type.String,
                        leadV5Amplitude: type.String,
                        isLeadV6: type.String,
                        leadV6Amplitude: type.String,
                        isLeadV7: type.String,
                        leadV7Amplitude: type.String,
                        isLeadV8: type.String,
                        leadV8Amplitude: type.String,
                        isLeadV9: type.String,
                        leadV9Amplitude: type.String
                    }
                }
            },
            tWaveChange: {
                isTWaveChange: type.String,
                changeDetail: {
                    isLeadI: type.String,
                    leadIAmplitude: type.String,
                    leadIWaveforms: type.String,
                    isLeadII: type.String,
                    leadIIAmplitude: type.String,
                    leadIIWaveforms: type.String,
                    isLeadIII: type.String,
                    leadIIIAmplitude: type.String,
                    leadIIIWaveforms: type.String,
                    isLeadAVF: type.String,
                    leadAVFAmplitude: type.String,
                    leadAVFWaveforms: type.String,
                    isLeadAVL: type.String,
                    leadAVLAmplitude: type.String,
                    leadAVLWaveforms: type.String,
                    isLeadAVR: type.String,
                    leadAVRAmplitude: type.String,
                    leadAVRWaveforms: type.String,
                    isLeadV1: type.String,
                    leadV1Amplitude: type.String,
                    leadV1Waveforms: type.String,
                    isLeadV2: type.String,
                    leadV2Amplitude: type.String,
                    leadV2Waveforms: type.String,
                    isLeadV3: type.String,
                    leadV3Amplitude: type.String,
                    leadV3Waveforms: type.String,
                    isLeadV4: type.String,
                    leadV4Amplitude: type.String,
                    leadV4Waveforms: type.String,
                    isLeadV5: type.String,
                    leadV5Amplitude: type.String,
                    leadV5Waveforms: type.String,
                    isLeadV6: type.String,
                    leadV6Amplitude: type.String,
                    leadV6Waveforms: type.String,
                    isLeadV7: type.String,
                    leadV7Amplitude: type.String,
                    leadV7Waveforms: type.String,
                    isLeadV8: type.String,
                    leadV8Amplitude: type.String,
                    leadV8Waveforms: type.String,
                    isLeadV9: type.String,
                    leadV9Amplitude: type.String,
                    leadV9Waveforms: type.String
                }
            },
            arrhythmia: {
                isArrhythmia: type.String,
                arrhythmiaTypes: type.String,
                arrhythmiaTypeOthers: type.String
            },
            isResultNormal: type.String,
            findings: type.String
        },
        exerciseEcg: {
            isExerciseAngina: type.String,
            exerciseDuration: type.String,
            maximalBloodPressure: type.String,
            minimalBloodPressure: type.String,
            stSegmentChange: {
                isStSegmentChange: type.String,
                stSegmentDepression: {
                    isStSegmentDepression: type.String,
                    duration: type.String,
                    changeDetail: {
                        isLeadI: type.String,
                        leadIAmplitude: type.String,
                        isLeadII: type.String,
                        leadIIAmplitude: type.String,
                        isLeadIII: type.String,
                        leadIIIAmplitude: type.String,
                        isLeadAVF: type.String,
                        leadAVFAmplitude: type.String,
                        isLeadAVL: type.String,
                        leadAVLAmplitude: type.String,
                        isLeadAVR: type.String,
                        leadAVRAmplitude: type.String,
                        isLeadV1: type.String,
                        leadV1Amplitude: type.String,
                        isLeadV2: type.String,
                        leadV2Amplitude: type.String,
                        isLeadV3: type.String,
                        leadV3Amplitude: type.String,
                        isLeadV4: type.String,
                        leadV4Amplitude: type.String,
                        isLeadV5: type.String,
                        leadV5Amplitude: type.String,
                        isLeadV6: type.String,
                        leadV6Amplitude: type.String,
                        isLeadV7: type.String,
                        leadV7Amplitude: type.String,
                        isLeadV8: type.String,
                        leadV8Amplitude: type.String,
                        isLeadV9: type.String,
                        leadV9Amplitude: type.String
                    }
                },
                stSegmentElevation: {
                    isStSegmentElevation: type.String,
                    duration: type.String,
                    changeDetail: {
                        isLeadI: type.String,
                        leadIAmplitude: type.String,
                        isLeadII: type.String,
                        leadIIAmplitude: type.String,
                        isLeadIII: type.String,
                        leadIIIAmplitude: type.String,
                        isLeadAVF: type.String,
                        leadAVFAmplitude: type.String,
                        isLeadAVL: type.String,
                        leadAVLAmplitude: type.String,
                        isLeadAVR: type.String,
                        leadAVRAmplitude: type.String,
                        isLeadV1: type.String,
                        leadV1Amplitude: type.String,
                        isLeadV2: type.String,
                        leadV2Amplitude: type.String,
                        isLeadV3: type.String,
                        leadV3Amplitude: type.String,
                        isLeadV4: type.String,
                        leadV4Amplitude: type.String,
                        isLeadV5: type.String,
                        leadV5Amplitude: type.String,
                        isLeadV6: type.String,
                        leadV6Amplitude: type.String,
                        isLeadV7: type.String,
                        leadV7Amplitude: type.String,
                        isLeadV8: type.String,
                        leadV8Amplitude: type.String,
                        isLeadV9: type.String,
                        leadV9Amplitude: type.String
                    }
                }
            },
            tWaveChange: {
                isTWaveChange: type.String,
                duration: type.String,
                changeDetail: {
                    isLeadI: type.String,
                    leadIAmplitude: type.String,
                    leadIWaveforms: type.String,
                    isLeadII: type.String,
                    leadIIAmplitude: type.String,
                    leadIIWaveforms: type.String,
                    isLeadIII: type.String,
                    leadIIIAmplitude: type.String,
                    leadIIIWaveforms: type.String,
                    isLeadAVF: type.String,
                    leadAVFAmplitude: type.String,
                    leadAVFWaveforms: type.String,
                    isLeadAVL: type.String,
                    leadAVLAmplitude: type.String,
                    leadAVLWaveforms: type.String,
                    isLeadAVR: type.String,
                    leadAVRAmplitude: type.String,
                    leadAVRWaveforms: type.String,
                    isLeadV1: type.String,
                    leadV1Amplitude: type.String,
                    leadV1Waveforms: type.String,
                    isLeadV2: type.String,
                    leadV2Amplitude: type.String,
                    leadV2Waveforms: type.String,
                    isLeadV3: type.String,
                    leadV3Amplitude: type.String,
                    leadV3Waveforms: type.String,
                    isLeadV4: type.String,
                    leadV4Amplitude: type.String,
                    leadV4Waveforms: type.String,
                    isLeadV5: type.String,
                    leadV5Amplitude: type.String,
                    leadV5Waveforms: type.String,
                    isLeadV6: type.String,
                    leadV6Amplitude: type.String,
                    leadV6Waveforms: type.String,
                    isLeadV7: type.String,
                    leadV7Amplitude: type.String,
                    leadV7Waveforms: type.String,
                    isLeadV8: type.String,
                    leadV8Amplitude: type.String,
                    leadV8Waveforms: type.String,
                    isLeadV9: type.String,
                    leadV9Amplitude: type.String,
                    leadV9Waveforms: type.String
                }
            },
            result: type.String,
            findings: type.String
        },
        holterEcg: {
            totalHeartbeats: type.String,
            averageHeartRate: type.String,
            maximalHeartRate: type.String,
            maximalHeartRateOccurrenceTime: type.String,
            minimalHeartRate: type.String,
            minimalHeartRateOccurrenceTime: type.String,
            arrhythmia: {
                isArrhythmia: type.String,
                frequentness: type.String,
                totalAbnormalHeartbeats: type.String,
                arrhythmiaTypes: [
                    {
                        arrhythmiaType: type.String,
                        arrhythmiaTypeOthers: type.String,
                        duration: type.String
                    }
                ]
            },
            pathologicalQWave: {
                isPathologicalQWave: type.String,
                frequentness: type.String,
                qWaveLeadsDetail: [
                    {
                        duration: type.String,
                        qWaveLeads: type.String
                    }
                ]
            },
            stSegmentChange: {
                isStSegmentChange: type.String,
                stSegmentDepression: {
                    isStSegmentDepression: type.String,
                    frequentness: type.String,
                    changesDetail: [
                        {
                            duration: type.String,
                            isLeadI: type.String,
                            leadIAmplitude: type.String,
                            isLeadII: type.String,
                            leadIIAmplitude: type.String,
                            isLeadIII: type.String,
                            leadIIIAmplitude: type.String,
                            isLeadAVF: type.String,
                            leadAVFAmplitude: type.String,
                            isLeadAVL: type.String,
                            leadAVLAmplitude: type.String,
                            isLeadAVR: type.String,
                            leadAVRAmplitude: type.String,
                            isLeadV1: type.String,
                            leadV1Amplitude: type.String,
                            isLeadV2: type.String,
                            leadV2Amplitude: type.String,
                            isLeadV3: type.String,
                            leadV3Amplitude: type.String,
                            isLeadV4: type.String,
                            leadV4Amplitude: type.String,
                            isLeadV5: type.String,
                            leadV5Amplitude: type.String,
                            isLeadV6: type.String,
                            leadV6Amplitude: type.String,
                            isLeadV7: type.String,
                            leadV7Amplitude: type.String,
                            isLeadV8: type.String,
                            leadV8Amplitude: type.String,
                            isLeadV9: type.String,
                            leadV9Amplitude: type.String
                        }
                    ]
                },
                stSegmentElevation: {
                    isStSegmentElevation: type.String,
                    frequentness: type.String,
                    changesDetail: [
                        {
                            duration: type.String,
                            isLeadI: type.String,
                            leadIAmplitude: type.String,
                            isLeadII: type.String,
                            leadIIAmplitude: type.String,
                            isLeadIII: type.String,
                            leadIIIAmplitude: type.String,
                            isLeadAVF: type.String,
                            leadAVFAmplitude: type.String,
                            isLeadAVL: type.String,
                            leadAVLAmplitude: type.String,
                            isLeadAVR: type.String,
                            leadAVRAmplitude: type.String,
                            isLeadV1: type.String,
                            leadV1Amplitude: type.String,
                            isLeadV2: type.String,
                            leadV2Amplitude: type.String,
                            isLeadV3: type.String,
                            leadV3Amplitude: type.String,
                            isLeadV4: type.String,
                            leadV4Amplitude: type.String,
                            isLeadV5: type.String,
                            leadV5Amplitude: type.String,
                            isLeadV6: type.String,
                            leadV6Amplitude: type.String,
                            isLeadV7: type.String,
                            leadV7Amplitude: type.String,
                            isLeadV8: type.String,
                            leadV8Amplitude: type.String,
                            isLeadV9: type.String,
                            leadV9Amplitude: type.String
                        }
                    ]
                }
            },
            tWaveChange: {
                isTWaveChange: type.String,
                frequentness: type.String,
                changesDetail: [
                    {
                        duration: type.String,
                        isLeadI: type.String,
                        leadIAmplitude: type.String,
                        leadIWaveforms: type.String,
                        isLeadII: type.String,
                        leadIIAmplitude: type.String,
                        leadIIWaveforms: type.String,
                        isLeadIII: type.String,
                        leadIIIAmplitude: type.String,
                        leadIIIWaveforms: type.String,
                        isLeadAVF: type.String,
                        leadAVFAmplitude: type.String,
                        leadAVFWaveforms: type.String,
                        isLeadAVL: type.String,
                        leadAVLAmplitude: type.String,
                        leadAVLWaveforms: type.String,
                        isLeadAVR: type.String,
                        leadAVRAmplitude: type.String,
                        leadAVRWaveforms: type.String,
                        isLeadV1: type.String,
                        leadV1Amplitude: type.String,
                        leadV1Waveforms: type.String,
                        isLeadV2: type.String,
                        leadV2Amplitude: type.String,
                        leadV2Waveforms: type.String,
                        isLeadV3: type.String,
                        leadV3Amplitude: type.String,
                        leadV3Waveforms: type.String,
                        isLeadV4: type.String,
                        leadV4Amplitude: type.String,
                        leadV4Waveforms: type.String,
                        isLeadV5: type.String,
                        leadV5Amplitude: type.String,
                        leadV5Waveforms: type.String,
                        isLeadV6: type.String,
                        leadV6Amplitude: type.String,
                        leadV6Waveforms: type.String,
                        isLeadV7: type.String,
                        leadV7Amplitude: type.String,
                        leadV7Waveforms: type.String,
                        isLeadV8: type.String,
                        leadV8Amplitude: type.String,
                        leadV8Waveforms: type.String,
                        isLeadV9: type.String,
                        leadV9Amplitude: type.String,
                        leadV9Waveforms: type.String
                    }
                ]
            },
            findings: type.String
        },
        ucgLVD: type.String,
        ucgEDV: type.String,
        ucgLVS: type.String,
        ucgESV: type.String,
        ucgLAD: type.String,
        ucgLVPW: type.String,
        ucgIVST: type.String,
        isLVEFLtFortyPercent: type.String,
        ucgEF: type.String,
        ucgRatioEToA: type.String,
        isLocalMotionAbnormality: type.String,
        localMotionAbnormalityParts: type.String,
        isVntricularAneurysm: type.String,
        vntricularAneurysmParts: type.String,
        isLeftVentricularThrombosis: type.String,
        leftVentricularThrombosisParts: type.String,
        ucgFindings: type.String,
        pciNum: type.String,
        pciDate: type.String,
        pciType: type.String,
        pciThrombolysisInterval: type.String,
        pciOnsetIntervalDay: type.String,
        pciOnsetIntervalHour: type.String,
        stayTimeCCU: type.String,
        stayTimeConduitRoom: type.String,
        stayTimeEmergencyCall: type.String,
        stayTimePrehospital: type.String,
        contrastMedia: type.String,
        contrastMediaOthers: type.String,
        coronaryDistributionType: type.String,
        isCoronaryMalformations: type.String,
        isGrade3Lesions: type.String,
        isBloodFlowTIMIGrade0to2: type.String,
        isCTO: type.String,
        isCollateralCirculation: type.String,
        pciPaths: type.String,
        implantedBracketCountLAD: type.String,
        implantedBracketCountLCX: type.String,
        implantedBracketCountLM: type.String,
        implantedBracketCountRCA: type.String,
        segmentalLesions: [
            {
                num: type.String,
                stenosis: type.String,
                length: type.String,
                shape: type.String,
                isCalcification: type.String,
                isOstialLesion: type.String,
                isThrombus: type.String,
                TIMIGrade: type.String,
                kindsOfLesions: type.String,
                pciGuidewire: type.String,
                balloon: type.String,
                stent: type.String
            }
        ]
    },
    admissionDiagnosis: {
        isMyocardialInfarction: type.String,
        myocardialInfarctionType: type.String,
        myocardialInfarctionPart: type.String,
        isAngina: type.String,
        anginaType: type.String,
        anginaCcs: type.String,
        isCoronaryMicrovascularDisease: type.String,
        isSilentMyocardialIschemia: type.String,
        isIschemicCardiomyopathy: type.String,
        isSuddenCoronaryDeath: type.String,
        isChestPainOfUnknownOrigin: type.String,
        isDiagnosisOthers: type.String,
        diagnosisOthers: type.String
    },
    dischargeDiagnosis: {
        isMyocardialInfarction: type.String,
        myocardialInfarctionType: type.String,
        myocardialInfarctionPart: type.String,
        isAngina: type.String,
        anginaType: type.String,
        anginaCcs: type.String,
        isCoronaryMicrovascularDisease: type.String,
        isSilentMyocardialIschemia: type.String,
        isIschemicCardiomyopathy: type.String,
        isSuddenCoronaryDeath: type.String,
        isChestPainOfUnknownOrigin: type.String,
        isDiagnosisOthers: type.String,
        diagnosisOthers: type.String
    }
});

module.exports = mongoose.model('record', recordSchema);