var emptyMr = {
    "basicInfo": {
        "admissionNum": "",
        "bedNum": "",
        "doctorId": "",
        "recorderId": "",
        "name": "",
        "medicalCardNum": "",
        "idNum": "",
        "cellphone1": "",
        "cellphone2": "",
        "telephone": "",
        "gender": "",
        "nationality": "",
        "birthProvince": "",
        "birthCity": "",
        "birthday": "",
        "profession": "",
        "addressProvince": "",
        "addressCity": "",
        "addressArea": "",
        "addressTown": "",
        "address": ""
    },
    "historyOfPresentIllness": {
        "careCauses": "",
        "careCauseOthers": "",
        "chestPain": {
            "timesPerDay": "",
            "timesPerWeek": "",
            "timesPerMonth": "",
            "timesPerYear": "",
            "onsetTime": "",
            "onsetTimeOthers": "",
            "diseaseBodyParts": [{
                    "bodyPartName": "",
                    "bodyPartNameOthers": "",
                    "qualityOfPain": "",
                    "qualityOfPainOthers": "",
                    "durationOfPain": "",
                    "durationOfPainOthers": "",
                    "painDegree": ""
                },
                {
                    "bodyPartName": "",
                    "bodyPartNameOthers": "",
                    "qualityOfPain": "",
                    "qualityOfPainOthers": "",
                    "durationOfPain": "",
                    "durationOfPainOthers": "",
                    "painDegree": ""
                }
            ],
            "relievingFactors": "",
            "relievingFactorsOthers": "",
            "precipitatingFactors": "",
            "precipitatingFactorsOthers": "",
            "radiationSites": "",
            "radiationSitesOthers": "",
            "simultaneousPhenomena": "",
            "simultaneousPhenomenonOthers": ""
        },
        "chestDistress": {
            "timesPerDay": "",
            "timesPerWeek": "",
            "timesPerMonth": "",
            "timesPerYear": "",
            "onsetTime": "",
            "onsetTimeOthers": "",
            "diseaseBodyParts": [{
                    "bodyPartName": "",
                    "bodyPartNameOthers": "",
                    "qualityOfPain": "",
                    "qualityOfPainOthers": "",
                    "durationOfPain": "",
                    "durationOfPainOthers": "",
                    "painDegree": ""
                },
                {
                    "bodyPartName": "",
                    "bodyPartNameOthers": "",
                    "qualityOfPain": "",
                    "qualityOfPainOthers": "",
                    "durationOfPain": "",
                    "durationOfPainOthers": "",
                    "painDegree": ""
                }
            ],
            "relievingFactors": "",
            "relievingFactorsOthers": "",
            "precipitatingFactors": "",
            "precipitatingFactorsOthers": "",
            "radiationSites": "",
            "radiationSitesOthers": "",
            "simultaneousPhenomena": "",
            "simultaneousPhenomenonOthers": ""
        },
        "dyspnea": {
            "timesPerDay": "",
            "timesPerWeek": "",
            "timesPerMonth": "",
            "timesPerYear": "",
            "onsetTime": "",
            "onsetTimeOthers": ""
        },
        "palpitation": {
            "timesPerDay": "",
            "timesPerWeek": "",
            "timesPerMonth": "",
            "timesPerYear": "",
            "onsetTime": "",
            "onsetTimeOthers": ""
        },
        "abnormalEcg": {
            "timesPerDay": "",
            "timesPerWeek": "",
            "timesPerMonth": "",
            "timesPerYear": "",
            "onsetTime": "",
            "onsetTimeOthers": ""
        }
    },
    "anamnesis": {
        "isLipidAbnormality": "",
        "lipidAbnormalityType": "",
        "lipidAbnormalityDuration": "",
        "isLipidAbnormalityUnderTreatment": "",
        "lipidAbnormalityDrugName": "",
        "isEssentialHypertension": "",
        "essentialHypertensionDuration": "",
        "maximumValue": "",
        "ordinaryValue": "",
        "isEssentialHypertensionUnderTreatment": "",
        "essentialHypertensionDrugName": "",
        "isDysglycemia": "",
        "dysglycemiaDuration": "",
        "dysglycemiaType": "",
        "isDiabetesMellitus": "",
        "isDiabetesMellitusUnderTreatment": "",
        "diabetesMellitusTreatmentMethod": "",
        "diabetesMellitusOralDrugName": "",
        "isGout": "",
        "goutDuration": "",
        "serumUricAcidLevel": "",
        "isRenalInsufficiency": "",
        "renalInsufficiencyDuration": "",
        "maximumCr": "",
        "recentCr": "",
        "renalInsufficiencyEtiology": "",
        "isOldMyocardialInfarction": "",
        "oldMyocardialInfarctionOnsetTimeYear": "",
        "oldMyocardialInfarctionOnsetTimeMonth": "",
        "oldMyocardialInfarctionOnsetFrequency": "",
        "oldMyocardialInfarctionLocation": "",
        "oldMyocardialInfarctionLocationOthers": "",
        "isPciHistory": "",
        "isCabgHistory": "",
        "isCasGt50History": "",
        "isAtrialFibrillation": "",
        "isOtherHeartDiseaseHistory": "",
        "otherHeartDiseaseType": "",
        "otherHeartDiseaseTypeOthers": "",
        "isDeepVenousThrombosis": "",
        "deepVenousThrombosisOnsetTimeYear": "",
        "deepVenousThrombosisOnsetTimeMonth": "",
        "deepVenousThrombosisInducements": "",
        "deepVenousThrombosisSymptoms": "",
        "deepVenousThrombosisDiagnosisResult": "",
        "isOldIschemicStroke": "",
        "oldIschemicStrokeTypes": [{
                "typeName": "",
                "onsetTimeYear": "",
                "onsetTimeMonth": "",
                "onsetFrequency": ""
            },
            {
                "typeName": "",
                "onsetTimeYear": "",
                "onsetTimeMonth": "",
                "onsetFrequency": ""
            }
        ],
        "isVascularDiseases": "",
        "vascularDiseasesTypes": "",
        "isHemorrhage": "",
        "hemorrhageTypes": [{
                "typeName": "",
                "onsetTime": "",
                "onsetFrequency": ""
            },
            {
                "typeName": "",
                "onsetTime": "",
                "onsetFrequency": ""
            }
        ],
        "isBleeding": "",
        "bleedingCauses": [{
                "cause": "",
                "onsetTime": ""
            },
            {
                "cause": "",
                "onsetTime": ""
            }
        ]
    },
    "riskFactors": {
        "isSomking": "",
        "smokingDuration": "",
        "piecesPerDay": "",
        "cigretteType": "",
        "cigretteTypeOthers": "",
        "isSmokingCessation": "",
        "smokingCessationDuration": "",
        "isDrinking": "",
        "drinkingDuration": "",
        "talesPerDay": "",
        "wineType": "",
        "wineTypeOthers": "",
        "isTemperance": "",
        "temperanceDuration": "",
        "drinkingAmount": "",
        "paddyPotato": "",
        "grainMixedBeans": "",
        "potato": "",
        "vegetables": "",
        "fruits": "",
        "livestockMeat": "",
        "aquaticProducts": "",
        "eggs": "",
        "milkProducts": "",
        "soybeansNuts": "",
        "salt": "",
        "sugar": "",
        "oil": "",
        "fatMeat": "",
        "visceral": "",
        "bloodType": "",
        "isLongtermPsychologicalStress": "",
        "isDepression": "",
        "exerciseType": "",
        "exerciseDuration": "",
        "exerciseMode": "",
        "exerciseModeOthers": "",
        "isCentralObesity": "",
        "centralObesityDuration": "",
        "height": "",
        "weight": "",
        "waistline": "",
        "neckCircumference": "",
        "hipline": ""
    },
    "familyHistory": {
        "prematureChd": {
            "isPrematureChd": "",
            "onsetMembers": [{
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": "",
                    "prematureChdType": ""
                },
                {
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": "",
                    "prematureChdType": ""
                }
            ]
        },
        "myocardialInfarction": {
            "ismyocardialInfarction": "",
            "onsetMembers": [{
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": ""
                },
                {
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": ""
                }
            ]
        },
        "suddenDeath": {
            "issuddenDeath": "",
            "onsetMembers": [{
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": "",
                    "etiology": "",
                    "etiologyOthers": ""
                },
                {
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": "",
                    "etiology": "",
                    "etiologyOthers": ""
                }
            ]
        },
        "ischemicStroke": {
            "isIschemicStroke": "",
            "onsetMembers": [{
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": ""
                },
                {
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": ""
                }
            ]
        },
        "hemorrhagicStroke": {
            "isHemorrhagicStroke": "",
            "onsetMembers": [{
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": ""
                },
                {
                    "onsetMember": "",
                    "gender": "",
                    "onsetAge": ""
                }
            ]
        }
    },
    "physicalExamination": {
        "bodyTemperature": "",
        "respiratoryRate": "",
        "isBreathSoundsNormal": "",
        "breathSoundsType": "",
        "breathSoundsPart": "",
        "isLungWetRales": "",
        "lungWetRalesRange": "",
        "lungWetRalesPart": "",
        "heartRate": "",
        "cardiacRhythm": "",
        "heartSoundS1Result": "",
        "isS3S4GallopRhythm": "",
        "pulse": "",
        "bloodPressure": "",
        "isEarLobeLongitudinalCrack": "",
        "earLobeLongitudinalCrackParts": "",
        "isSkinYellowPigmentTumor": "",
        "skinYellowPigmentTumorParts": "",
        "isAlopecia": "",
        "alopeciaParts": ""
    },
    "routineExamination": {
        "TC": "",
        "TG": "",
        "LDL": "",
        "HDL": "",
        "notHDL": "",
        "bloodGlucoseFasting": "",
        "isSerumMyocardialNecrosisMarkers": "",
        "myocardialCK": "",
        "myocardialCKMB": "",
        "myocardialCTnI": "",
        "myocardialMb": "",
        "isInflammatoryMarkers": "",
        "inflammationHsCRP": "",
        "inflammationIL6": "",
        "inflammationIL1Beta": "",
        "inflammationTNFAlpha": "",
        "heartFailureNTproBNP": "",
        "electrolyteNa": "",
        "electrolyteK": "",
        "electrolyteCa": "",
        "electrolyteCl": "",
        "isLiverFunction": "",
        "totalProtein": "",
        "albumin": "",
        "totalBilirubin": "",
        "directBilirubin": "",
        "indirectBilirubin": "",
        "ALT": "",
        "AST": "",
        "isRenalFunction": "",
        "Cr": "",
        "UA": "",
        "BUN": "",
        "GFR": "",
        "isHepatorenalDisease": "",
        "APTT": "",
        "PT": "",
        "TT": "",
        "FIB": "",
        "dDimer": "",
        "INR": "",
        "isINRStable": "",
        "redBloodCellCount": "",
        "redBloodCellSpecificVolume": "",
        "HGB": "",
        "leukocyteCount": "",
        "neutrophil": "",
        "eosinophil": "",
        "basophil": "",
        "lymphocyte": "",
        "monocyte": "",
        "isQualitativePlatelet": "",
        "plateletCountPLT": "",
        "MPV": "",
        "PDW": "",
        "PARADP": "",
        "PAREpinephrine": "",
        "PARArachidonicAcid": "",
        "PARCollagen": "",
        "PARRistocetin": ""
    },
    "specialExamination": {
        "ecg": {
            "pathologicalQWave": {
                "isPathologicalQWave": "",
                "qWaveLeads": ""
            },
            "stSegmentChange": {
                "isStSegmentChange": "",
                "stSegmentDepression": {
                    "isStSegmentDepression": "",
                    "changeDetail": {
                        "isLeadI": "",
                        "leadIAmplitude": "",
                        "isLeadII": "",
                        "leadIIAmplitude": "",
                        "isLeadIII": "",
                        "leadIIIAmplitude": "",
                        "isLeadAVF": "",
                        "leadAVFAmplitude": "",
                        "isLeadAVL": "",
                        "leadAVLAmplitude": "",
                        "isLeadAVR": "",
                        "leadAVRAmplitude": "",
                        "isLeadV1": "",
                        "leadV1Amplitude": "",
                        "isLeadV2": "",
                        "leadV2Amplitude": "",
                        "isLeadV3": "",
                        "leadV3Amplitude": "",
                        "isLeadV4": "",
                        "leadV4Amplitude": "",
                        "isLeadV5": "",
                        "leadV5Amplitude": "",
                        "isLeadV6": "",
                        "leadV6Amplitude": "",
                        "isLeadV7": "",
                        "leadV7Amplitude": "",
                        "isLeadV8": "",
                        "leadV8Amplitude": "",
                        "isLeadV9": "",
                        "leadV9Amplitude": ""
                    }
                },
                "stSegmentElevation": {
                    "isStSegmentElevation": "",
                    "changeDetail": {
                        "isLeadI": "",
                        "leadIAmplitude": "",
                        "isLeadII": "",
                        "leadIIAmplitude": "",
                        "isLeadIII": "",
                        "leadIIIAmplitude": "",
                        "isLeadAVF": "",
                        "leadAVFAmplitude": "",
                        "isLeadAVL": "",
                        "leadAVLAmplitude": "",
                        "isLeadAVR": "",
                        "leadAVRAmplitude": "",
                        "isLeadV1": "",
                        "leadV1Amplitude": "",
                        "isLeadV2": "",
                        "leadV2Amplitude": "",
                        "isLeadV3": "",
                        "leadV3Amplitude": "",
                        "isLeadV4": "",
                        "leadV4Amplitude": "",
                        "isLeadV5": "",
                        "leadV5Amplitude": "",
                        "isLeadV6": "",
                        "leadV6Amplitude": "",
                        "isLeadV7": "",
                        "leadV7Amplitude": "",
                        "isLeadV8": "",
                        "leadV8Amplitude": "",
                        "isLeadV9": "",
                        "leadV9Amplitude": ""
                    }
                }
            },
            "tWaveChange": {
                "isTWaveChange": "",
                "changeDetail": {
                    "isLeadI": "",
                    "leadIAmplitude": "",
                    "leadIWaveforms": "",
                    "isLeadII": "",
                    "leadIIAmplitude": "",
                    "leadIIWaveforms": "",
                    "isLeadIII": "",
                    "leadIIIAmplitude": "",
                    "leadIIIWaveforms": "",
                    "isLeadAVF": "",
                    "leadAVFAmplitude": "",
                    "leadAVFWaveforms": "",
                    "isLeadAVL": "",
                    "leadAVLAmplitude": "",
                    "leadAVLWaveforms": "",
                    "isLeadAVR": "",
                    "leadAVRAmplitude": "",
                    "leadAVRWaveforms": "",
                    "isLeadV1": "",
                    "leadV1Amplitude": "",
                    "leadV1Waveforms": "",
                    "isLeadV2": "",
                    "leadV2Amplitude": "",
                    "leadV2Waveforms": "",
                    "isLeadV3": "",
                    "leadV3Amplitude": "",
                    "leadV3Waveforms": "",
                    "isLeadV4": "",
                    "leadV4Amplitude": "",
                    "leadV4Waveforms": "",
                    "isLeadV5": "",
                    "leadV5Amplitude": "",
                    "leadV5Waveforms": "",
                    "isLeadV6": "",
                    "leadV6Amplitude": "",
                    "leadV6Waveforms": "",
                    "isLeadV7": "",
                    "leadV7Amplitude": "",
                    "leadV7Waveforms": "",
                    "isLeadV8": "",
                    "leadV8Amplitude": "",
                    "leadV8Waveforms": "",
                    "isLeadV9": "",
                    "leadV9Amplitude": "",
                    "leadV9Waveforms": ""
                }
            },
            "arrhythmia": {
                "isArrhythmia": "",
                "arrhythmiaTypes": "",
                "arrhythmiaTypeOthers": ""
            },
            "isResultNormal": "",
            "findings": ""
        },
        "exerciseEcg": {
            "isExerciseAngina": "",
            "exerciseDuration": "",
            "maximalBloodPressure": "",
            "minimalBloodPressure": "",
            "stSegmentChange": {
                "isStSegmentChange": "",
                "stSegmentDepression": {
                    "isStSegmentDepression": "",
                    "duration": "",
                    "changeDetail": {
                        "isLeadI": "",
                        "leadIAmplitude": "",
                        "isLeadII": "",
                        "leadIIAmplitude": "",
                        "isLeadIII": "",
                        "leadIIIAmplitude": "",
                        "isLeadAVF": "",
                        "leadAVFAmplitude": "",
                        "isLeadAVL": "",
                        "leadAVLAmplitude": "",
                        "isLeadAVR": "",
                        "leadAVRAmplitude": "",
                        "isLeadV1": "",
                        "leadV1Amplitude": "",
                        "isLeadV2": "",
                        "leadV2Amplitude": "",
                        "isLeadV3": "",
                        "leadV3Amplitude": "",
                        "isLeadV4": "",
                        "leadV4Amplitude": "",
                        "isLeadV5": "",
                        "leadV5Amplitude": "",
                        "isLeadV6": "",
                        "leadV6Amplitude": "",
                        "isLeadV7": "",
                        "leadV7Amplitude": "",
                        "isLeadV8": "",
                        "leadV8Amplitude": "",
                        "isLeadV9": "",
                        "leadV9Amplitude": ""
                    }
                },
                "stSegmentElevation": {
                    "isStSegmentElevation": "",
                    "duration": "",
                    "changeDetail": {
                        "isLeadI": "",
                        "leadIAmplitude": "",
                        "isLeadII": "",
                        "leadIIAmplitude": "",
                        "isLeadIII": "",
                        "leadIIIAmplitude": "",
                        "isLeadAVF": "",
                        "leadAVFAmplitude": "",
                        "isLeadAVL": "",
                        "leadAVLAmplitude": "",
                        "isLeadAVR": "",
                        "leadAVRAmplitude": "",
                        "isLeadV1": "",
                        "leadV1Amplitude": "",
                        "isLeadV2": "",
                        "leadV2Amplitude": "",
                        "isLeadV3": "",
                        "leadV3Amplitude": "",
                        "isLeadV4": "",
                        "leadV4Amplitude": "",
                        "isLeadV5": "",
                        "leadV5Amplitude": "",
                        "isLeadV6": "",
                        "leadV6Amplitude": "",
                        "isLeadV7": "",
                        "leadV7Amplitude": "",
                        "isLeadV8": "",
                        "leadV8Amplitude": "",
                        "isLeadV9": "",
                        "leadV9Amplitude": ""
                    }
                }
            },
            "tWaveChange": {
                "isTWaveChange": "",
                "duration": "",
                "changeDetail": {
                    "isLeadI": "",
                    "leadIAmplitude": "",
                    "leadIWaveforms": "",
                    "isLeadII": "",
                    "leadIIAmplitude": "",
                    "leadIIWaveforms": "",
                    "isLeadIII": "",
                    "leadIIIAmplitude": "",
                    "leadIIIWaveforms": "",
                    "isLeadAVF": "",
                    "leadAVFAmplitude": "",
                    "leadAVFWaveforms": "",
                    "isLeadAVL": "",
                    "leadAVLAmplitude": "",
                    "leadAVLWaveforms": "",
                    "isLeadAVR": "",
                    "leadAVRAmplitude": "",
                    "leadAVRWaveforms": "",
                    "isLeadV1": "",
                    "leadV1Amplitude": "",
                    "leadV1Waveforms": "",
                    "isLeadV2": "",
                    "leadV2Amplitude": "",
                    "leadV2Waveforms": "",
                    "isLeadV3": "",
                    "leadV3Amplitude": "",
                    "leadV3Waveforms": "",
                    "isLeadV4": "",
                    "leadV4Amplitude": "",
                    "leadV4Waveforms": "",
                    "isLeadV5": "",
                    "leadV5Amplitude": "",
                    "leadV5Waveforms": "",
                    "isLeadV6": "",
                    "leadV6Amplitude": "",
                    "leadV6Waveforms": "",
                    "isLeadV7": "",
                    "leadV7Amplitude": "",
                    "leadV7Waveforms": "",
                    "isLeadV8": "",
                    "leadV8Amplitude": "",
                    "leadV8Waveforms": "",
                    "isLeadV9": "",
                    "leadV9Amplitude": "",
                    "leadV9Waveforms": ""
                }
            },
            "result": "",
            "findings": ""
        },
        "holterEcg": {
            "totalHeartbeats": "",
            "averageHeartRate": "",
            "maximalHeartRate": "",
            "maximalHeartRateOccurrenceTime": "",
            "minimalHeartRate": "",
            "minimalHeartRateOccurrenceTime": "",
            "arrhythmia": {
                "isArrhythmia": "",
                "frequentness": "",
                "totalAbnormalHeartbeats": "",
                "arrhythmiaTypes": [{
                        "arrhythmiaType": "",
                        "arrhythmiaTypeOthers": "",
                        "duration": ""
                    },
                    {
                        "arrhythmiaType": "",
                        "arrhythmiaTypeOthers": "",
                        "duration": ""
                    },
                    {
                        "arrhythmiaType": "",
                        "arrhythmiaTypeOthers": "",
                        "duration": ""
                    }
                ]
            },
            "pathologicalQWave": {
                "isPathologicalQWave": "",
                "frequentness": "",
                "qWaveLeadsDetail": [{
                        "duration": "",
                        "qWaveLeads": ""
                    },
                    {
                        "duration": "",
                        "qWaveLeads": ""
                    },
                    {
                        "duration": "",
                        "qWaveLeads": ""
                    }
                ]
            },
            "stSegmentChange": {
                "isStSegmentChange": "",
                "stSegmentDepression": {
                    "isStSegmentDepression": "",
                    "frequentness": "",
                    "changesDetail": [{
                            "duration": "",
                            "isLeadI": "",
                            "leadIAmplitude": "",
                            "isLeadII": "",
                            "leadIIAmplitude": "",
                            "isLeadIII": "",
                            "leadIIIAmplitude": "",
                            "isLeadAVF": "",
                            "leadAVFAmplitude": "",
                            "isLeadAVL": "",
                            "leadAVLAmplitude": "",
                            "isLeadAVR": "",
                            "leadAVRAmplitude": "",
                            "isLeadV1": "",
                            "leadV1Amplitude": "",
                            "isLeadV2": "",
                            "leadV2Amplitude": "",
                            "isLeadV3": "",
                            "leadV3Amplitude": "",
                            "isLeadV4": "",
                            "leadV4Amplitude": "",
                            "isLeadV5": "",
                            "leadV5Amplitude": "",
                            "isLeadV6": "",
                            "leadV6Amplitude": "",
                            "isLeadV7": "",
                            "leadV7Amplitude": "",
                            "isLeadV8": "",
                            "leadV8Amplitude": "",
                            "isLeadV9": "",
                            "leadV9Amplitude": ""
                        },
                        {
                            "duration": "",
                            "isLeadI": "",
                            "leadIAmplitude": "",
                            "isLeadII": "",
                            "leadIIAmplitude": "",
                            "isLeadIII": "",
                            "leadIIIAmplitude": "",
                            "isLeadAVF": "",
                            "leadAVFAmplitude": "",
                            "isLeadAVL": "",
                            "leadAVLAmplitude": "",
                            "isLeadAVR": "",
                            "leadAVRAmplitude": "",
                            "isLeadV1": "",
                            "leadV1Amplitude": "",
                            "isLeadV2": "",
                            "leadV2Amplitude": "",
                            "isLeadV3": "",
                            "leadV3Amplitude": "",
                            "isLeadV4": "",
                            "leadV4Amplitude": "",
                            "isLeadV5": "",
                            "leadV5Amplitude": "",
                            "isLeadV6": "",
                            "leadV6Amplitude": "",
                            "isLeadV7": "",
                            "leadV7Amplitude": "",
                            "isLeadV8": "",
                            "leadV8Amplitude": "",
                            "isLeadV9": "",
                            "leadV9Amplitude": ""
                        }
                    ]
                },
                "stSegmentElevation": {
                    "isStSegmentElevation": "",
                    "frequentness": "",
                    "changesDetail": [{
                            "duration": "",
                            "isLeadI": "",
                            "leadIAmplitude": "",
                            "isLeadII": "",
                            "leadIIAmplitude": "",
                            "isLeadIII": "",
                            "leadIIIAmplitude": "",
                            "isLeadAVF": "",
                            "leadAVFAmplitude": "",
                            "isLeadAVL": "",
                            "leadAVLAmplitude": "",
                            "isLeadAVR": "",
                            "leadAVRAmplitude": "",
                            "isLeadV1": "",
                            "leadV1Amplitude": "",
                            "isLeadV2": "",
                            "leadV2Amplitude": "",
                            "isLeadV3": "",
                            "leadV3Amplitude": "",
                            "isLeadV4": "",
                            "leadV4Amplitude": "",
                            "isLeadV5": "",
                            "leadV5Amplitude": "",
                            "isLeadV6": "",
                            "leadV6Amplitude": "",
                            "isLeadV7": "",
                            "leadV7Amplitude": "",
                            "isLeadV8": "",
                            "leadV8Amplitude": "",
                            "isLeadV9": "",
                            "leadV9Amplitude": ""
                        },
                        {
                            "duration": "",
                            "isLeadI": "",
                            "leadIAmplitude": "",
                            "isLeadII": "",
                            "leadIIAmplitude": "",
                            "isLeadIII": "",
                            "leadIIIAmplitude": "",
                            "isLeadAVF": "",
                            "leadAVFAmplitude": "",
                            "isLeadAVL": "",
                            "leadAVLAmplitude": "",
                            "isLeadAVR": "",
                            "leadAVRAmplitude": "",
                            "isLeadV1": "",
                            "leadV1Amplitude": "",
                            "isLeadV2": "",
                            "leadV2Amplitude": "",
                            "isLeadV3": "",
                            "leadV3Amplitude": "",
                            "isLeadV4": "",
                            "leadV4Amplitude": "",
                            "isLeadV5": "",
                            "leadV5Amplitude": "",
                            "isLeadV6": "",
                            "leadV6Amplitude": "",
                            "isLeadV7": "",
                            "leadV7Amplitude": "",
                            "isLeadV8": "",
                            "leadV8Amplitude": "",
                            "isLeadV9": "",
                            "leadV9Amplitude": ""
                        }
                    ]
                }

            },
            "tWaveChange": {
                "isTWaveChange": "",
                "frequentness": "",
                "changesDetail": [{
                        "duration": "",
                        "isLeadI": "",
                        "leadIAmplitude": "",
                        "leadIWaveforms": "",
                        "isLeadII": "",
                        "leadIIAmplitude": "",
                        "leadIIWaveforms": "",
                        "isLeadIII": "",
                        "leadIIIAmplitude": "",
                        "leadIIIWaveforms": "",
                        "isLeadAVF": "",
                        "leadAVFAmplitude": "",
                        "leadAVFWaveforms": "",
                        "isLeadAVL": "",
                        "leadAVLAmplitude": "",
                        "leadAVLWaveforms": "",
                        "isLeadAVR": "",
                        "leadAVRAmplitude": "",
                        "leadAVRWaveforms": "",
                        "isLeadV1": "",
                        "leadV1Amplitude": "",
                        "leadV1Waveforms": "",
                        "isLeadV2": "",
                        "leadV2Amplitude": "",
                        "leadV2Waveforms": "",
                        "isLeadV3": "",
                        "leadV3Amplitude": "",
                        "leadV3Waveforms": "",
                        "isLeadV4": "",
                        "leadV4Amplitude": "",
                        "leadV4Waveforms": "",
                        "isLeadV5": "",
                        "leadV5Amplitude": "",
                        "leadV5Waveforms": "",
                        "isLeadV6": "",
                        "leadV6Amplitude": "",
                        "leadV6Waveforms": "",
                        "isLeadV7": "",
                        "leadV7Amplitude": "",
                        "leadV7Waveforms": "",
                        "isLeadV8": "",
                        "leadV8Amplitude": "",
                        "leadV8Waveforms": "",
                        "isLeadV9": "",
                        "leadV9Amplitude": "",
                        "leadV9Waveforms": ""
                    },
                    {
                        "duration": "",
                        "isLeadI": "",
                        "leadIAmplitude": "",
                        "leadIWaveforms": "",
                        "isLeadII": "",
                        "leadIIAmplitude": "",
                        "leadIIWaveforms": "",
                        "isLeadIII": "",
                        "leadIIIAmplitude": "",
                        "leadIIIWaveforms": "",
                        "isLeadAVF": "",
                        "leadAVFAmplitude": "",
                        "leadAVFWaveforms": "",
                        "isLeadAVL": "",
                        "leadAVLAmplitude": "",
                        "leadAVLWaveforms": "",
                        "isLeadAVR": "",
                        "leadAVRAmplitude": "",
                        "leadAVRWaveforms": "",
                        "isLeadV1": "",
                        "leadV1Amplitude": "",
                        "leadV1Waveforms": "",
                        "isLeadV2": "",
                        "leadV2Amplitude": "",
                        "leadV2Waveforms": "",
                        "isLeadV3": "",
                        "leadV3Amplitude": "",
                        "leadV3Waveforms": "",
                        "isLeadV4": "",
                        "leadV4Amplitude": "",
                        "leadV4Waveforms": "",
                        "isLeadV5": "",
                        "leadV5Amplitude": "",
                        "leadV5Waveforms": "",
                        "isLeadV6": "",
                        "leadV6Amplitude": "",
                        "leadV6Waveforms": "",
                        "isLeadV7": "",
                        "leadV7Amplitude": "",
                        "leadV7Waveforms": "",
                        "isLeadV8": "",
                        "leadV8Amplitude": "",
                        "leadV8Waveforms": "",
                        "isLeadV9": "",
                        "leadV9Amplitude": "",
                        "leadV9Waveforms": ""
                    }
                ]
            },
            "findings": ""
        },
        "ucgLVD": "",
        "ucgEDV": "",
        "ucgLVS": "",
        "ucgESV": "",
        "ucgLAD": "",
        "ucgLVPW": "",
        "ucgIVST": "",
        "isLVEFLtFortyPercent": "",
        "ucgEF": "",
        "ucgRatioEToA": "",
        "isLocalMotionAbnormality": "",
        "localMotionAbnormalityParts": "",
        "isVntricularAneurysm": "",
        "vntricularAneurysmParts": "",
        "isLeftVentricularThrombosis": "",
        "leftVentricularThrombosisParts": "",
        "ucgFindings": "",
        "pciNum": "",
        "pciDate": "",
        "pciType": "",
        "pciThrombolysisInterval": "",
        "pciOnsetIntervalDay": "",
        "pciOnsetIntervalHour": "",
        "stayTimeCCU": "",
        "stayTimeConduitRoom": "",
        "stayTimeEmergencyCall": "",
        "stayTimePrehospital": "",
        "contrastMedia": "",
        "contrastMediaOthers": "",
        "coronaryDistributionType": "",
        "isCoronaryMalformations": "",
        "isGrade3Lesions": "",
        "isBloodFlowTIMIGrade0to2": "",
        "isCTO": "",
        "isCollateralCirculation": "",
        "pciPaths": "",
        "implantedBracketCountLAD": "",
        "implantedBracketCountLCX": "",
        "implantedBracketCountLM": "",
        "implantedBracketCountRCA": "",
        "segmentalLesions": [{
                "num": "",
                "stenosis": "",
                "length": "",
                "shape": "",
                "isCalcification": "",
                "isOstialLesion": "",
                "isThrombus": "",
                "TIMIGrade": "",
                "kindsOfLesions": "",
                "pciGuidewire": "",
                "balloon": "",
                "stent": ""
            },
            {
                "num": "",
                "stenosis": "",
                "length": "",
                "shape": "",
                "isCalcification": "",
                "isOstial_lesion": "",
                "isThrombus": "",
                "TIMIGrade": "",
                "kindsOfLesions": "",
                "pciGuidewire": "",
                "balloon": "",
                "stent": ""
            }
        ]
    },
    "admissionDiagnosis": {
        "isMyocardialInfarction": "",
        "myocardialInfarctionType": "",
        "myocardialInfarctionPart": "",
        "isAngina": "",
        "anginaType": "",
        "anginaCcs": "",
        "isCoronaryMicrovascularDisease": "",
        "isSilentMyocardialIschemia": "",
        "isIschemicCardiomyopathy": "",
        "isSuddenCoronaryDeath": "",
        "isChestPainOfUnknownOrigin": "",
        "isDiagnosisOthers": "",
        "diagnosisOthers": ""
    },
    "dischargeDiagnosis": {
        "isMyocardialInfarction": "",
        "myocardialInfarctionType": "",
        "myocardialInfarctionPart": "",
        "isAngina": "",
        "anginaType": "",
        "anginaCcs": "",
        "isCoronaryMicrovascularDisease": "",
        "isSilentMyocardialIschemia": "",
        "isIschemicCardiomyopathy": "",
        "isSuddenCoronaryDeath": "",
        "isChestPainOfUnknownOrigin": "",
        "isDiagnosisOthers": "",
        "diagnosisOthers": ""
    }
}

module.exports = emptyMr;